# Generated by Django 5.2.1 on 2025-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
