# Generated by Django 5.2.1 on 2025-05-09 22:24

import apps.profiles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.profiles.models.user_directory_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_profile_picture', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Swipe',
        ),
    ]
