# Generated by Django 5.2.1 on 2025-05-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_gender_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='DEBUG_BIO_FIELD', null=True),
        ),
    ]
