# Generated by Django 5.2.1 on 2025-05-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_city_remove_profile_location_profile_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_profile_picture',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_profile_avatar',
            field=models.BooleanField(default=False, help_text='Is this the main profile picture?'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
