# Generated by Django 5.2.1 on 2025-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('EVERYONE', 'Everyone')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
    ]
