FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Собираем статику (будет пересобираться при каждом билде)
RUN python manage.py collectstatic --noinput

# Запуск через gunicorn
CMD ["gunicorn", "TinderCloneProject.wsgi:application", "--bind", "0.0.0.0:8000"]