# Generated by Django 5.2.1 on 2025-05-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='user1_id_lt_user2_id_match',
        ),
        migrations.AlterField(
            model_name='match',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_record', to='matches.conversation'),
        ),
    ]
