# Generated by Django 5.2.1 on 2025-05-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_options_and_more'),
        ('profiles', '0002_profile_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='other_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
