# Generated by Django 5.2.1 on 2025-05-14 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_conversation_other_profile'),
        ('profiles', '0003_profile_blocked_users_profile_matches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to='profiles.profile')),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swiper', 'profile')},
            },
        ),
    ]
